version: '3.3'

services:

  app:
    build: .
    image: oceanexplorer/todoapi

  unit:
    image: microsoft/dotnet
    volumes:
      - .:/usr/todoapi
    working_dir: /usr/todoapi/tests/TodoApi.Tests.Unit
    command: "dotnet test"

  staging-dep:
    image: oceanexplorer/todoapi
    container_name: todoapi
    ports:
      - 5050:5050
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:5050
      DATABASE_SA_PASSWORD: Testing123
      DATABASE_HOST: postgres-server 
    depends_on:
      - db

  staging:
    image: microsoft/dotnet    
    volumes:  
      - .:/usr/todoapi
    working_dir: /usr/todoapi/tests/TodoApi.Tests.Integration
    command: "dotnet test"
    environment:
      DATABASE_SA_PASSWORD: Testing123
      DATABASE_HOST: postgres-server

  production:
    image: microsoft/dotnet
    volumes:
      - .:/usr/todoapi    
    environment:
      - HOST_IP=${HOST_IP}
    working_dir: /usr/todoapi/tests/TodoApi.Tests.Production
    network_mode: host
    command: "dotnet test"

  production-loop:
    image: microsoft/dotnet
    volumes:
      - .:/usr/todoapi    
    environment:
      - HOST_IP=${HOST_IP}
      - DURATION=1
    working_dir: /usr/todoapi/tests/TodoApi.Tests.Production
    network_mode: host
    command: "dotnet test"

  db:
    image: postgres 
    restart: always    
    ports:
      - 5432:5432
    container_name: postgres-server
    environment:
      POSTGRES_PASSWORD: Testing123
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:    