version: '3.3'

services:

  app:
    build: .
    image: oceanexplorer/todoapi

  unit:
    image: microsoft/dotnet
    volumes:
      - .:/usr/todoapi
    working_dir: /usr/todoapi/tests/TodoApi.Tests.Unit
    command: "dotnet test"

  staging-dep:
    image: oceanexplorer/todoapi
    container_name: todoapi
    ports:
      - 5000:5000
    environment:
      DATABASE_SA_PASSWORD: Testing123
      DATABASE_HOST: postgres-server 
    depends_on:
      - db

  staging:
    image: microsoft/dotnet    
    volumes:  
      - .:/usr/todoapi
    working_dir: /usr/todoapi/tests/TodoApi.Tests.Integration
    command: "dotnet test"
    environment:
      DATABASE_SA_PASSWORD: Testing123
      DATABASE_HOST: postgres-server 

  db:
    image: postgres
    restart: always    
    ports:
      - 5432:5432
    container_name: postgres-server
    environment:
      POSTGRES_PASSWORD: Testing123
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:    